# This is an example of the secrets.toml file you'll need to create in Streamlit Cloud
# Do not add your actual API key here - this is just a template

# API Keys
GEMINI_API_KEY = "your-gemini-api-key-here"

# Add any other secrets your application needs
